### ISSUE TITLE
How to scroll to specific segment (first page) programmatically?

### ISSUE THREAD

**Issue by yao23** [MichaelHuyp/YPSegmentController#1]
For example in the readme, there are 10 pages for 10 companies, when I scroll to page 5, then there is no content and I set up a button which can direct to page 1 after click, how to implement scrolling to page 1?

I saw 

```
- (void)segmentBar:(YPSegmentBar *)segmentBar didSelectedIndex:(NSInteger)toIndex fromIndex:(NSInteger)fromIndex
{
    [self showChildVCViewsAtIndex:toIndex];
}
```

but showChildVCViewsAtIndex() is not a public function.

**Comment by MichaelHuyp** [comment]
@yao23 
````objc
self.segmentController.segmentBar.selectIndex = 0;
````

**Comment by yao23** [comment]
It works perfect, you'd better add more instruction for this property in readme file, there are many people use it.

**Comment by MichaelHuyp** [comment]
ok... This is just an early version,waiting for improvement
